tickers:
  - NOW
  - ADBE
  - CRM
  - ORCL
  - MSFT
  - ANET
  - PLTR
  - NVDA
  - AVGO
  - MRVL
  - MU
  - COHR
  - LITE
  - NOK
  - FN
  - VST
  - CEG
  - ETN
  - COIN
  - HOOD
  - NVO
  - ISRG
  - AAPL
  - GOOG
  - IBM
  - INTU
  - WDAY
